# STAGE 1
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json .
COPY yarn.lock .
RUN yarn
COPY . .
RUN yarn build

# STAGE 2
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]